### ISSUE TITLE
Can't checkout with crypto on Mumbai 

### ISSUE THREAD

**Issue by k-nrd** [paperxyz/react-client-sdk#56]
How to reproduce:

1. Follow paper docs, deploy contract on mumbai and register etc
2. Connect to mumbai through whatever means (I used rainbowkit fwiw)
3. Get the `Signer` object, pass that in to `CheckoutWithEth` and pass a callback to `setUpUserPayingWalletSigner` logging the `chainId` that comes out
4. Attempt to checkout with eth, verify that even though `Signer` wants to transact in Mumbai, `setUpUserPayingWalletSigner` will log `chainId === 5`. Whenever you try to complete the payment, you'll be prompted to switch to Goerli.

I've read through `Provider`, `checkoutWithEth/index.ts` and `ViewPricingDetails.tsx`, doesn't look like the bug is in here. It seems that whatever data is coming from the `iframe` is wrong.

**Comment by ElasticBottle** [comment]
Hey @k-nrd paying with Eth is either on mainnet (for production checkouts) or Goerli (for test checkouts).

The rationale being that anyone can pay with Eth on it's main chain regardless of the chain where the NFT drop is  happening on.

Hope this helps!
