### ISSUE TITLE
Restrict ethers to v5

### ISSUE THREAD

**Issue by ghardin1314** [paperxyz/react-client-sdk#75]
Getting an error from the latest versions of your package `0.8.14`. 

![image](https://user-images.githubusercontent.com/54160127/218628891-441bd1f1-878f-4c97-98d6-ce1134244d7f.png)

I believe its because you do not restrict the major version of `ethers` to v5. There is now a beta version of `ethers` `6.0.3` available on npm but I dont think its really ready for production and has many breaking changes. I believe your build is including this version and is breaking the build of our apps.

**Comment by ghardin1314** [comment]
Build works for us by reverting to `0.8.9`

**Comment by ElasticBottle** [comment]
Hey thanks for this! We've updated the semver to lock it to v5 for now
